### ISSUE TITLE
Contribution Guideline

### ISSUE THREAD

**Issue by abtonc** [tpecholt/imrad#13]
I would love to contribute but I think a proper contribution guideline is needed for the future.

**Comment by tpecholt** [comment]
Hi Arda,

in which way would you want to contribute? Do you have a specific feature
or improvement in your mind?

Tomas

**Comment by JustCallMeRay** [comment]
Can't speak for Arda but I would like to change the header extensions to `.hpp` (rather than `.h`) and change the cmake files to use `find_package` so I can use a package manager like Conan.

I think the need for a contributing guide is required even if it is just a "do the usual" in a couple of sentences. The main thing I find helpful is a merge request template and something that tells me what branch to merge into/base a pr off.
