### ISSUE TITLE
after build get error

### ISSUE THREAD

**Issue by apol3t** [tpecholt/imrad#19]
After building with cmake, the program does not open and I get this error. Could you add a tutorial on how to build your project?
![image](https://github.com/tpecholt/imrad/assets/46138078/20608216-9e5d-4319-8f1f-157346222229)

**Comment by tpecholt** [comment]
Hi apol3t! It looks like ImRAD can't load the fonts. Maybe because the style folder was not copied automatically or if you are running it from VS the working directory was not set.

I commited some build related improvements, added a short How to build description to the README and uploaded updated binaries. Hope it helps.

**Comment by apol3t** [comment]
this helped a lot thank you so much
