### ISSUE TITLE
Crashes & Unable to run

### ISSUE THREAD

**Issue by joi32f23** [tpecholt/imrad#21]
Hi, I'm unable to run the prebuild binaries on windows 11, I'm also unable to run it by building it using VS 2022 Community edition. I've followed the instructions as well as I could.

Below is a video showcasing exactly what I've done from each step.
[video showcasing the problem on youtube](https://youtu.be/aR2agcxCOzQ)

Any help would be appreciated.

**Comment by tpecholt** [comment]
Hi and thanks for the report! 

Can you try to install MS redistributable [DLLs](https://aka.ms/vs/17/release/vc_redist.x64.exe) to see if the problem with running prebuilt binaries goes away? I see you even tried to run it from command line where it usually reveals missing DLL issues but the command line runs differently in windows 11 so it may not reveal anything.

To fix the build first I see you are configuring ARM64 configuration is it correct? I haven't try to build for this platform but it may work.

Then I see you built the whole solution which is good but the INSTALL project is still not built. This project prepares the target directory structure so it has to be built as well. It may require running VS in administrator mode otherwise it could refuse to copy files.

Finally if you want to run ImRAD from VS you correctly set imrad as a startup project but you will also need to set its working directory to the installed path so that the required files (fonts, styles...) are found. 

Please let me know if the above suggestions work and I will update the README accordingly.

**Comment by joi32f23** [comment]
Thanks for getting back to me so quickly.

Just wanted to let you know that installing the Microsoft redistributable DLLs did the trick for the binaries. But I still had some hiccups with Visual Studio, even with your suggestions. Interestingly, everything worked fine on my main Windows desktop. So, I'm wondering if the issue might be with virtual machines running Windows 11 on the Apple MacBook Pro 2021 M1 Pro – like the one I showed in the video.

For now, I'll be using my Windows desktop for this. Just wanted to give a shout out and say thanks for creating such a cool project. It's really impressive, and I'm looking forward to seeing where you take it next.

Thanks again!

**Comment by Emilprivate** [comment]
To add to this, would be really cool to see Apple silicon support.

**Comment by tpecholt** [comment]
The problem is I don't own Apple HW to build it and from what I know Apple makes it nearly impossible to develop without it. But I would accept a patch.

I updated the releases with MS redistributable download.

**Comment by Super-Genius** [comment]
Just updated the build pull request to also support Apple Silicon and x86_64 in fat binary.
