### ISSUE TITLE
Where is misc/cpp/imgui_stdlib.h?

### ISSUE THREAD

**Issue by RicoP** [tpecholt/imrad#3]
imrad.h includes misc/cpp/imgui_stdlib.h

I don't know where this file is. Do I need an extra dependency?

**Comment by ocornut** [comment]
It is in the imgui project:
https://github.com/ocornut/imgui/tree/master/misc/cpp

I guess the project expect you to have your imgui/ folder in include paths.

**Comment by tpecholt** [comment]
imgui_stdlib.h is needed as it implements std::string version of Input widget which would otherwise be cumbersome to write.

Let me know if there are any issues with this approach otherwise I will close the ticket.

I plan to move other #includes from the generated header file to imrad.h as well I think it will make it look more concise that way
